### ISSUE TITLE
Add labels under main workflow buttons

### ISSUE THREAD

**Issue by stevendlander** [GitHubRGI/swagd#11]
Currently there are no labels under the workflow buttons in the main GUI window for Tiling, Packaging, or Viewing.

Add either on-hover labels or fixed static labels under these buttons.

**Comment by duffmeans** [comment]
There are on-hover labels. Do these not work on Linux?

**Comment by stevendlander** [comment]
Hmm, I guess not.  Are they tooltip style labels?  For instance, does a small window with the label show up at the mouse cursor location or is it showed at a fixed point on the window?

**Comment by duffmeans** [comment]
Tooltip style, under the mouse.
