### ISSUE TITLE
Achieve GDAL stability on all platforms

### ISSUE THREAD

**Issue by LLambertRGi** [GitHubRGI/swagd#16]
Document process for achieving stable install of GDAL on Windows/Linux.  Incorporate into POM if necessary.

**Comment by stevendlander** [comment]
Depends on #63 (putting jar libraries shaded into final jar/exe)

**Comment by stevendlander** [comment]
Attempting OSGeo4W (32bit) installer, which has packages that support gdal-java bindings as well as a swig package

**Comment by stevendlander** [comment]
OSGeo4W 64-bit has no pre-built gdal dlls or jar.  GDAL was compiled on a 64 bit machine using MSVS 2013 Express Edition with SWIG bindings to Java.

Adding a lib folder to RGISuite that will contain both gdal.jar and all x64 gdal dlls necessary for running the application.  Also, the gdal data folder will be added to the classpath.

**Comment by stevendlander** [comment]
RGISuite/lib *must* be put into the windows path variable and eclipse must be restarted to take effect.

**Comment by stevendlander** [comment]
Adding documentation for creating a sane build/run environment with GDAL in the SWAGD wiki area: https://github.com/GitHubRGI/swagd/wiki/Creating-A-Sane-GDAL-Environment-(Windows-64-bit)

**Comment by stevendlander** [comment]
Added documentation to the wiki for a build/run environment on Linux. https://github.com/GitHubRGI/swagd/wiki/Creating-A-Sane-GDAL-Environment-(Linux-x64)
