### ISSUE TITLE
Change Packaging option for image type to allow jpeg and png

### ISSUE THREAD

**Issue by Jal3k5** [GitHubRGI/swagd#171]

**Comment by stevendlander** [comment]
What is the status of this?  Shows as the last issue open for Release 1.0

**Comment by Jal3k5** [comment]
I was waiting on a code review. I believe I mentioned this to you on Friday, it just seems to have been forgotten in the mix of getting tiling and coverity done.

**Comment by Jal3k5** [comment]
Sorry I didn’t mean to come off so rudely in my last email…I was going for PC/Formal/Polite and reading it back it just sounds awful.  I just meant we got busy and it fell through the cracks.

**Comment by stevendlander** [comment]
LOL Jen, no offence taken.  Also, respond directly to me in email, right now your emails are getting posted to the issue on Github.  :)

**Comment by LLambertRGi** [comment]
I still have some minor issues with this pull request. Let's wait to discuss at the morning meeting
