### ISSUE TITLE
Could not initialize class utility.gdalUtility

### ISSUE THREAD

**Issue by grl-sage** [GitHubRGI/swagd#351]
Used Tile tool.  Input PNG and set reference and received error.

![swagd error](https://cloud.githubusercontent.com/assets/13260540/12879261/a319033c-cdfe-11e5-85bf-a007fe215445.png)

**Comment by stevendlander** [comment]
This is an issue stemming from the SWAGD installer not correctly telling the JAR where the GDAL resources are on the system or, in some cases, failing to install GDAL at all.

Expect a new installer to be created today that will address this particular error.  Thanks!

**Comment by grl-sage** [comment]
OK.  I'll keep an eye out for it.

**Comment by grl-sage** [comment]
Was a new installer created?

**Comment by stevendlander** [comment]
Not yet unfortunately.  I anticipate being able to get to this in a few days to a few weeks.  I will keep you informed via this issue.

**Comment by stevendlander** [comment]
WiX installer is not properly including sub-installers from the Resources folder.

**Comment by stevendlander** [comment]
tagging @phillyphanatic for notification when completed.

**Comment by stevendlander** [comment]
New installer available here: https://github.com/GitHubRGI/swagd/releases/tag/v1.4
