### ISSUE TITLE
Add check to GeoPackageTiles.addMatrix to make sure the bounds match the tile matrix set bounds

### ISSUE THREAD

**Issue by LLambertRGi** [GitHubRGI/swagd#74]

**Comment by LLambertRGi** [comment]
The changes have been made, but now a bunch of tiles tests fail because they were using bogus values for tile matrix set bounds.  The tests will need to be changed to make sure tile matrices being added have bounds that match the tile matrix set bounds.

**Comment by Jal3k5** [comment]
41dcaf8
