### ISSUE TITLE
Extension Class .equals bug

### ISSUE THREAD

**Issue by Jal3k5** [GitHubRGI/swagd#75]
The .equals method isn't returning the expected values because it is comparing Scope as an object.  Either need to override equals in the Scope class or turn Scope toString then compare

**Comment by LLambertRGi** [comment]
Waiting for the build to be fixed to test

**Comment by LLambertRGi** [comment]
The build is fixed, just waiting to hear from Jen that tests exist that test this, and that they pass :>
